services:
  db:
    image: mysql:8
    container_name: hauidoc-db
    restart: no
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env.db

  phpMyAdmin:
    image: phpmyadmin
    container_name: hauidoc-phpmyadmin
    restart: no
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    depends_on:
      - db

  web:
    build: .
    container_name: hauidoc-web
    restart: no
    ports:
      - "3000:3000"
    env_file:
      - .env.docker.local
    depends_on:
      - db
      - libreoffice
    # environment:
    #   NODE_ENV: "production"

  libreoffice:
    build: ../libre-convert
    container_name: hauidoc-libreoffice
    restart: no
    depends_on:
      - db

volumes:
  mysql_data:
